# Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx4g

# Gradle
org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=2g -Dfile.encoding=UTF-8

# Kotlin/Native
kotlin.native.concurrent.numberOfWorkers=2

# KSP (important for CI stability)
ksp.incremental=false

# Android
android.nonTransitiveRClass=true
android.useAndroidX=true

# Gradle performance (keep)
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.workers.max=2
